### ISSUE TITLE
Long "chown" process on startup

### ISSUE THREAD

**Issue by praet0ri4n** [tuxgasy/docker-dolibarr#15]
Hi,
thank you for this docker image. I was able to spin it up successfully.
But on every docker start there is a looong "chown" process running on the dolibarr container blocking the startup process, which now takes 10-15 minutes.. Killing the process leads to maria_db database not starting properly.
Can I avoid this chown?
Thank you!
Filip.

**Comment by tuxgasy** [comment]
Hi,
I do not see a long process.
To avoid this chown, you can edit the file [docker-run.sh](https://github.com/tuxgasy/docker-dolibarr/blob/master/images/10.0.3/docker-run.sh).
Bye

**Comment by ma0dubois** [comment]
Hi @praet0ri4n 

You did not share the global web folder via a Docker volume ?

Because [here](https://github.com/tuxgasy/docker-dolibarr/blob/master/images/10.0.3/docker-run.sh#L10) we can that the chown is on all /var/www folder and not /var/www/html

If this is the case and you have a folder other than Dolibarr's, it may be longer.

**Comment by praet0ri4n** [comment]
Hi @ma0dubois 
thanks for your response! No, at first I did not use a shared volume.. in that case the chown process was running for 10+ minutes.. But as I wanted to have access to the dolibarr and mysql files from outside the container I attached a local dir to /var/www/html and the chown problem was solved, startup within few seconds... I did not investigate further what it was causing.

**Comment by ma0dubois** [comment]
ok good.

close your issue pls
