### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by TechServiceConseil** [tuxgasy/docker-dolibarr#83]
Hello!

First of all, Thank you for the work.

I try to run on an orange pi lite 2 today and I'm facing a issue. The SQL conatiner work fine but the dolibarr one won't start.
I use d your compose with secret example with 15.0.1-php7.4 tag. The error is "standard_init_linux.go:228: exec user process caused: exec format error". I read some stuff about a portage of the work made by Monogramm at this link [https://github.com/Monogramm/docker-dolibarr/issues/54].
Can you tell me if you have make some change related to that thread in your repo pls. I don't know if it's a bug or if it just have not be implemented yet.  If not, do you plan to it and info in the linked thread still be valable?

Bye

**Comment by mathieupotier** [comment]
Hi @TechServiceConseil ,

It seems that this monogramm repository is different from this one.
But let me explain for your problem : these images are built from official apache docker image, as far as I know these images are ARM compliant (so far ... ^_^)
Maybe the pi you're using is not enough hardware compatible with those latest ARM images : Raspberry made several hardware upgrade since Pi2. Didi you try to install on a Pi4 computer ? (Unfortunatly, I don't have any remaining Pi4 myself for making this test ... ^_^)

I'll double check the libraries that we're using, but I'm not sure to find a potential issue with these ...
Any idea @tuxgasy ?

Regards,

**Comment by tuxgasy** [comment]
Hi all

@TechServiceConseil
Images now support ARM architecture (arm/v7 and arm64). I tested on Raspberry Pi (with Raspberry Pi OS 64bit) and it works fine.
Can you test ?

**Comment by TechServiceConseil** [comment]
Hello,
 
I try it and it's works fine on an orangepi lite 2 wich have an all winner H6.

Thank you for the job.

I noticed that i can not add the entire www folder of Dolibarr and the html one give me just the custom folder inside.
Can you implement the possibility to add that volume. That gonna avoid some connection to the remote container when you want modify some stuff in the core.

I gonna report here when i gonna try on my orange pi zero 2 wich have an all winner H616.

Thank you again.
