### ISSUE TITLE
SSL with file and not certbot

### ISSUE THREAD

**Issue by TechServiceConseil** [tuxgasy/docker-dolibarr#91]
Hello,

Like always, thank you for the job first. 

I wanna know if it's possible to you to provide me an example to use SSL with file in a volume. I always find something with a certbot but my PI is the CA :).

If you have not trusted CA, you can not have the good warning for https in chrome but that crypt the data and is firefox you can put that CA as an exeption and that crypt the traffic to. For now if you want the sensor like camera it's ok with firefox put with chrome yo have to handle  Insecure origins treated as secure put if you had the ip of your CA is good too.
So all work in fact with an auto genrate certificat execpt the certbot and i dont need it.

Could you please show me the way to put that file in a volume?

Have a good day.

**Comment by mathieupotier** [comment]
Hi,

This image is not providing any SSL, it goes against the SOLID principles ^_^
SSL has to be performed by your implementation into your stack.
I personnaly use traefik in mine, you can have a slight example here : https://github.com/tuxgasy/docker-dolibarr/tree/master/examples/with-rp-traefik

But you'll probably have to figure out by yourself, as my stack is not yours.
I'm using traefik RP to serve SSL in front of my dolibarr, traefik is configured to generate a valid SSL cert with certbot using my DNS provider Cloudflare.
Traefik can generate a selfsigned certificate anyway, it just throw an error on your browser, but the connection remain secured if you're trusting yourself ^_^.

The SSL implementation will not be integrated in this image because it's out of scope, these images are providing Dolibarr instance run (non SSL), serving SSL has to be performed in front of this image

Regards
